remote_theme: pmarsceill/just-the-docs

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-7YFR550ESE


logo: "/img/horiz_black.png"

footer-content: "Subscribe to Stations Signal for periodic updates and free resources."
